const express = require('express')
const router = express.Router()
const fs = require('fs')

const { cekKey, checkLimit } = require('../database/db')
const { getFile } = require('../lib/function')
const { cekUsername, cekRequest, cekEmail } = require('../database/premium')
const { artinama, artimimpi, ramaljodoh, nomorhoki, zodiak, kecocokan_nama, kecocokan_nama_pasangan, tanggal_jadian_pernikahan, sifat_usaha_bisnis, rejeki_hoki_weton, pekerjaan_weton_lahir, ramalan_nasib, cek_potensi_penyakit, arti_kartu_tarot, petung_hari_baik, hari_sangar_taliwangke, primbon_hari_naas, rahasia_naga_hari, primbon_arah_rejeki, ramalan_peruntungan, weton_jawa, sifat_karakter_tanggal_lahir, potensi_keberuntungan, primbon_memancing_ikan, seberapagay } = require('../features/primbon')
const { katahilih, katahuluh, katahalah, kataheleh, kataholoh } = require('../features/vokal')
const { waifu2, neko2, shinobu2, megumin, bully, cuddle, cry, awoo, kiss, lick, slap, bonk2, yeet, bite, pat, hug, smug, blush, wave, smile, nom, highfive, cringe, dance, happy, glomp, handhold } = require('../features/nsfwsfw')
const { tebakgambar, asahotak, susunkata, tebakaplikasi, tebakwaifu, tebakanime, tebakjenaka, tebaklagu, siapakahaku, tebakkata, tebakkalimat, tebaktebakan, tekateki, tebakbendera, tebakkimia, caklontong, tebaklirik, family100, tebakkabupaten, truthdare } = require('../features/entertainment')
const { jeni, jiso, justina, rose, ryujin, indonesia, japan, korea, thailand, vietnam, china, asupan, loliv, kayes2, hijaber, geayubi, bocil, ukhty, rikagusriani, notnot2, asupantiktok } = require('../features/asupan')
const { quotesanime2, pantun, katailham, katagalau, katabijak2, faktaunik, quotespubg, quotesislamic, quotes, puisi, truth, dare, quotesanime, katabucin, motivasi, katasindiran, nickff, katacinta, katasenja, fml, katahacker } = require('../features/randomtext')
const { styletext, wangy, wangy2, nenen, simp, sherk, tokohindo, gi, giwp, herodetail, herolist, ssweb, simisimi } = require('../features/other')
const { aesthetic, blackpink, bonekachucky, wallpapercyberspace, wallpaperhacker, wallpapertechnology, wallpaperpubg, wallpaperprogramming, wallpapermountain, wallpaperislamic, darkjoke, darkmeme, meme, memesuki, doraemon, pentol, motor, mobil, kucing, kpop, satanic, renungan, pokemon, quotesimage, quotesyt, ppcouple, anjing, yulibocil, tatasurya } = require('../features/randomimage')
const { husbu, kuriyama, kosaki, gremory, chitanda, ahegao, rem, nishimiya, nekonime, natsukawa, kuroha, yatogami, tomori, sagiri, ayuzawa, emilia, chiho, akira, akiyama, ana, asuna, boruto, chitoge, deidara, eba, elaina, erza, hestia, hinata, inori, isuzu, itachi, itori, kaga, kagura, kakasi, kaori, keneki, kotori, kurumi, madara, mikasa, miku, minato, nezuko, onepiece, rize, sakura, sasuke, shina, shinka, shinomiya, shizuka, shota, tejina, toukachan, tsunade, yotsuba, yuki, yumeko, yuri, loli, milf, cosplay, waifu, naruto, neko, shinobu } = require('../features/randomanime')
const { surah2, sholat2, wirid, tahlil, tafsirsurah, alquranaudio, kisahnabi, hadist, alquran, listsurah, randomquran, surah, sholat, niatsholat, bacaansholat, ayatkursi, asmaulhusna } = require('../features/muslim')
const { gsmarena2, ringtone, pinterest2, alphacoders2, pinterest, wikimedia, amino, android1, tiktoksearch, zerochan, jobstreet, rexdl, emoji, gsmarena, apkmirror, bacaresep, goresearch, cariresep, playstore, sticker, pixivsearch, happymod, apkmody, moddroid, sfilesearch, chordlagu, konachan, alphacoders, lirik, wallpaperscraft, wallpapercave, domainsearch, cekdomain, mcpedl, steleSearch, stickerline, servermc, linkwa, gimage, ytsearch, jalantikus, palingmurah, google, wiki  } = require('../features/searching')
const { tiktok, tiktoknowm, tiktokwm, youtube, ytplaymp4,  ytplaymp3, ytmp3, ytmp4, twitter, tiktokmate, twitter2, solidfiles, zippyshare, xnxxdl, xnxxsearch, goredl, tiktokaudio, savefrom, tiktokmusically, pindl, mediafire, soundcloud, instagram, instastory, sfiledl, stickerDl, telesticker, facebook, facebook2, instagram2, aiovideodl, pixiv, pindl2, linestickerdownload, soundcloud2, twitter3, imgurdl, imdbdl, likeedl, cocofun, umma, instastory2, youtube2, anonfiledl, tiktokder, dddtik, snapinsta,  keeptiktok, snaptik, googledrive, snapsave, ssstik, tiktok2 } = require('../features/downloader')
const { ghstalk, tiktokStalk, twitterStalk, ffstalk, npmstalk } = require('../features/stalking')
const { cerpennn } = require('../features/cerpen')

     router.get('/checkapikey', async (req, res) => {
         let apikey = req.query.apikey
         if (!apikey) return res.status(400).send({ status: 400, message: 'apikey parameter cannot be empty', result: 'error' })
         let check = await cekKey(apikey)
         if (!check) return res.status(404).send({ status: 404, message: `apikey ${apikey} not found, please register first.` })
         let limit = await checkLimit(apikey)
         let username = await cekUsername(apikey)
         let request = await cekRequest(apikey)
         let email = await cekEmail(apikey)
         res.status(200).send({ status: 200, message: 'succes', result: { username: username, request: request, email: email, limit: limit }})
     })
     
     router.get('/toFile', async(req, res) => {
         let url = req.query.url 
         const buffer = await getFile(url)
         fs.writeFileSync(__path+ `/tmp/temp.${buffer.ext}`, buffer.data)
         res.sendFile(__path+ `/tmp/temp.${buffer.ext}`)
     })
     
     // Downloader
     router.get('/download/tiktok', tiktok)
     router.get('/download/tiktok2', tiktok2)
     router.get('/download/tiktoknowm', tiktoknowm)
     router.get('/download/tiktokwm', tiktokwm)
     router.get('/download/tiktokaudio', tiktokaudio)
     router.get('/download/tiktokmusically', tiktokmusically)
     router.get('/download/tiktokmate', tiktokmate)
     router.get('/download/savefrom', savefrom)
     router.get('/download/youtube', youtube)
     router.get('/download/youtube2', youtube2)
     router.get('/download/ytplaymp4', ytplaymp4)
     router.get('/download/ytplaymp3', ytplaymp3)
     router.get('/download/ytmp3', ytmp3)
     router.get('/download/ytmp4', ytmp4)
     router.get('/download/twitter', twitter)
     router.get('/download/solidfiles', solidfiles)
     router.get('/download/twitter2', twitter2)
     router.get('/download/twitter3', twitter3)
     router.get('/download/zippyshare', zippyshare)
     router.get('/download/xnxxdl', xnxxdl)
     router.get('/download/xnxxsearch', xnxxsearch)
     router.get('/download/pindl', pindl)
     router.get('/download/pindl2', pindl2)
     router.get('/download/mediafire', mediafire)
     router.get('/download/scdl', soundcloud)
     router.get('/download/scdl2', soundcloud2)
     router.get('/download/igdl', instagram)
     router.get('/download/igdl2', instagram2)
     router.get('/download/igstory', instastory)
     router.get('/download/igstory2', instastory2)
     router.get('/download/sfiledl', sfiledl)
     router.get('/download/stickerdl', stickerDl)
     router.get('/download/telesticker', telesticker)
     router.get('/download/linesticker', linestickerdownload)
     router.get('/download/fbdl', facebook)
     router.get('/download/fbdl2', facebook2)          
     router.get('/download/aiovideodl', aiovideodl)
     router.get('/download/pixiv', pixiv)
     router.get('/download/goredl', goredl)          
     router.get('/download/imgur', imgurdl)          
     router.get('/download/imdb', imdbdl)          
     router.get('/download/likee', likeedl)          
     router.get('/download/cocofun', cocofun)               
     router.get('/download/umma', umma)               
     router.get('/download/anonfiledl', anonfiledl)                    
     router.get('/download/snapinsta', snapinsta)               
     router.get('/download/dddtik', dddtik)               
     router.get('/download/tiktokder', tiktokder)               
     router.get('/download/keeptiktok', keeptiktok)               
     router.get('/download/snaptik', snaptik)               
     router.get('/download/googledrive', googledrive)               
     router.get('/download/snapsave', snapsave)               
     router.get('/download/ssstik', ssstik)               

 // Searching
     router.get('/search/pinterest', pinterest)
     router.get('/search/pinterest2', pinterest2)
     router.get('/search/sticker', sticker)
     router.get('/search/pixivsearch', pixivsearch)
     router.get('/search/happymod', happymod)
     router.get('/search/apkmody', apkmody)
     router.get('/search/moddroid', moddroid)
     router.get('/search/sfilesearch', sfilesearch)
     router.get('/search/servermc', servermc)
     router.get('/search/linkwa', linkwa)
     router.get('/search/apkmirror', apkmirror)     
     router.get('/search/cariresep', cariresep)     
     router.get('/search/bacaresep', bacaresep)     
     router.get('/search/lirik', lirik)     
     router.get('/search/wikimedia', wikimedia)     
     router.get('/search/goresearch', goresearch)
     router.get('/search/zerochan', zerochan)
     router.get('/search/jobstreet', jobstreet)
     router.get('/search/emoji', emoji)
     router.get('/search/gsmarena', gsmarena)
     router.get('/search/gsmarena2', gsmarena2)
     router.get('/search/android1', android1)     
     router.get('/search/rexdl', rexdl)
     router.get('/search/chordlagu', chordlagu)
     router.get('/search/playstore', playstore)
     router.get('/search/mcpedl', mcpedl)
     router.get('/search/jalantikus', jalantikus)
     router.get('/search/palingmurah', palingmurah)
     router.get('/search/konachan', konachan)
     router.get('/search/alphacoders', alphacoders)
     router.get('/search/alphacoders2', alphacoders2)
     router.get('/search/wallpapercave', wallpapercave)
     router.get('/search/wallpaperscraft', wallpaperscraft)
     router.get('/search/domainsearch', domainsearch)
     router.get('/search/cekdomain', cekdomain)
     router.get('/search/stelesearch', steleSearch)
     router.get('/search/stickerline', stickerline)
     router.get('/search/gimage', gimage)
     router.get('/search/ytsearch', ytsearch)
     router.get('/search/google', google)
     router.get('/search/wikipedia', wiki)     
     router.get('/search/amino', amino)
     router.get('/search/ringtone', ringtone)     

     // Muslim
     router.get('/muslim/asmaulhusna', asmaulhusna)
     router.get('/muslim/bacaansholat', bacaansholat)
     router.get('/muslim/niatsholat', niatsholat)
     router.get('/muslim/wirid', wirid)
     router.get('/muslim/tahlil', tahlil)
     router.get('/muslim/ayatkursi', ayatkursi)
     router.get('/muslim/jadwalsholat', sholat)
     router.get('/muslim/jadwalsholat2', sholat2)
     router.get('/muslim/tafsirsurah', tafsirsurah)
     router.get('/muslim/surah', surah)
     router.get('/muslim/surah2', surah2)
     router.get('/muslim/listsurah', listsurah)
     router.get('/muslim/randomquran', randomquran)
     router.get('/muslim/hadist', hadist)
     router.get('/muslim/alquran', alquran)
     router.get('/muslim/kisahnabi', kisahnabi)
     router.get('/muslim/alquranaudio', alquranaudio)
     
//Random Anime
     router.get('/randomanime/waifu', waifu)
     router.get('/randomanime/husbu', husbu)
     router.get('/randomanime/loli', loli)
     router.get('/randomanime/naruto', naruto)
     router.get('/randomanime/milf', milf)
     router.get('/randomanime/cosplay', cosplay)
     router.get('/randomanime/ayuzawa', ayuzawa)
     router.get('/randomanime/akiyama', akiyama)
     router.get('/randomanime/ana', ana)
     router.get('/randomanime/asuna', asuna)
     router.get('/randomanime/boruto', boruto)
     router.get('/randomanime/chitoge', chitoge)
     router.get('/randomanime/deidara', deidara)
     router.get('/randomanime/eba', eba)
     router.get('/randomanime/elaina', elaina)
     router.get('/randomanime/erza', erza)
     router.get('/randomanime/hestia', hestia)
     router.get('/randomanime/hinata', hinata)
     router.get('/randomanime/inori', inori)
     router.get('/randomanime/isuzu', isuzu)
     router.get('/randomanime/itachi', itachi)
     router.get('/randomanime/itori', itori)
     router.get('/randomanime/kaga', kaga)
     router.get('/randomanime/kagura', kagura)
     router.get('/randomanime/kakasi', kakasi)
     router.get('/randomanime/kaori', kaori)
     router.get('/randomanime/keneki', keneki)
     router.get('/randomanime/kotori', kotori)
     router.get('/randomanime/kurumi', kurumi)
     router.get('/randomanime/madara', madara)
     router.get('/randomanime/mikasa', mikasa)
     router.get('/randomanime/miku', miku)
     router.get('/randomanime/minato', minato)
     router.get('/randomanime/nezuko', nezuko)
     router.get('/randomanime/onepiece', onepiece)
     router.get('/randomanime/rize', rize)
     router.get('/randomanime/sakura', sakura)
     router.get('/randomanime/sasuke', sasuke)
     router.get('/randomanime/shina', shina)
     router.get('/randomanime/shinka', shinka)
     router.get('/randomanime/shinomiya', shinomiya)
     router.get('/randomanime/shizuka', shizuka)
     router.get('/randomanime/shota', shota)
     router.get('/randomanime/tejina', tejina)
     router.get('/randomanime/toukachan', toukachan)
     router.get('/randomanime/tsunade', tsunade)
     router.get('/randomanime/yotsuba', yotsuba)
     router.get('/randomanime/yuki', yuki)
     router.get('/randomanime/yumeko', yumeko)
     router.get('/randomanime/yuri', yuri)
     router.get('/randomanime/emilia', emilia)
     router.get('/randomanime/akira', akira)
     router.get('/randomanime/chiho', chiho)    
     router.get('/randomanime/neko', neko)
     router.get('/randomanime/shinobu', shinobu)
     router.get('/randomanime/ahegao', ahegao)
     router.get('/randomanime/chitanda', chitanda)
     router.get('/randomanime/gremory', gremory)
     router.get('/randomanime/kosaki', kosaki)
     router.get('/randomanime/kuriyama', kuriyama)
     router.get('/randomanime/kuroha', kuroha)
     router.get('/randomanime/natsukawa', natsukawa)
     router.get('/randomanime/nekonime', nekonime)
     router.get('/randomanime/nishimiya', nishimiya)
     router.get('/randomanime/rem', rem)
     router.get('/randomanime/sagiri', sagiri)
     router.get('/randomanime/tomori', tomori)
     router.get('/randomanime/yatogami', yatogami)

//stalking
   router.get('/stalking/ghstalk', ghstalk)
   router.get('/stalking/tiktokstalk', tiktokStalk)
   router.get('/stalking/twitterStalk', twitterStalk)
   router.get('/stalking/ffstalk', ffstalk)
router.get('/stalking/npmstalk', npmstalk)

 //random image
     router.get('/randomimage/aesthetic', aesthetic)
     router.get('/randomimage/blackpink', blackpink)
     router.get('/randomimage/bonekachucky', bonekachucky)
     router.get('/randomimage/wallpapercyberspace', wallpapercyberspace)
     router.get('/randomimage/wallpaperhacker', wallpaperhacker)
     router.get('/randomimage/wallpapertechnology', wallpapertechnology)
     router.get('/randomimage/wallpaperpubg', wallpaperpubg)
     router.get('/randomimage/wallpaperprogramming', wallpaperprogramming)
     router.get('/randomimage/wallpaperislamic', wallpaperislamic)
     router.get('/randomimage/wallpapermountain', wallpapermountain)
     router.get('/randomimage/darkjoke', darkjoke)
     router.get('/randomimage/darkmeme', darkmeme)
     router.get('/randomimage/meme', meme)
     router.get('/randomimage/memesuki', memesuki)
     router.get('/randomimage/kucing', kucing)
     router.get('/randomimage/doraemon', doraemon)
     router.get('/randomimage/pentol', pentol)
     router.get('/randomimage/motor', motor)
     router.get('/randomimage/mobil', mobil)
     router.get('/randomimage/kpop', kpop)
     router.get('/randomimage/satanic', satanic)
     router.get('/randomimage/renungan', renungan)
     router.get('/randomimage/pokemon', pokemon)
     router.get('/randomimage/quotesimage', quotesimage)
     router.get('/randomimage/quotesyt', quotesyt)
     router.get('/randomimage/ppcouple', ppcouple)
     router.get('/randomimage/anjing', anjing)
     router.get('/randomimage/yulibocil', yulibocil)
     router.get('/randomimage/tatasurya', tatasurya)
     
// Other
     router.get('/other/wangy', wangy)
     router.get('/other/wangy2', wangy2)
     router.get('/other/nenen', nenen)
     router.get('/other/simp', simp)
     router.get('/other/sherk', sherk)
     router.get('/other/genshin', gi)
     router.get('/other/genshinweapon', giwp)
     router.get('/other/herodetail', herodetail)
     router.get('/other/herolist', herolist)
     router.get('/other/ssweb', ssweb)
     router.get('/other/tokohindo', tokohindo)
     router.get('/other/styletext', styletext)
     router.get('/other/simi-simi', simisimi)

//randomtext
   router.get('/randomtext/pantun', pantun)
   router.get('/randomtext/puisi', puisi)
   router.get('/randomtext/faktaunik', faktaunik)
   router.get('/randomtext/katabijak', katabijak2)
   router.get('/randomtext/katagalau', katagalau)
   router.get('/randomtext/katailham', katailham)
   router.get('/randomtext/quotes', quotes)
   router.get('/randomtext/quotespubg', quotespubg)
   router.get('/randomtext/quotesislamic', quotesislamic)
   router.get('/randomtext/motivasi', motivasi)
   router.get('/randomtext/quotesanime', quotesanime)
   router.get('/randomtext/quotesanime2', quotesanime2)
   router.get('/randomtext/dare', dare)
   router.get('/randomtext/truth', truth)
   router.get('/randomtext/katabucin', katabucin)
   router.get('/randomtext/katasenja', katasenja)
   router.get('/randomtext/katacinta', katacinta)
   router.get('/randomtext/katasindiran', katasindiran)
   router.get('/randomtext/katahacker', katahacker)
   router.get('/randomtext/fml', fml)
   router.get('/randomtext/nickff', nickff)

//Asupan
     router.get('/asupan', asupan)
     router.get('/asupan/tiktok', asupantiktok)
     router.get('/asupan/bocil', bocil)
     router.get('/asupan/geayubi', geayubi)
     router.get('/asupan/hijaber', hijaber)
     router.get('/asupan/kayes', kayes2)
     router.get('/asupan/loli', loliv)
     router.get('/asupan/notnot', notnot2)
     router.get('/asupan/rikagusriani', rikagusriani)
     router.get('/asupan/ukhty', ukhty)
     router.get('/cecan/china', china)
     router.get('/cecan/indonesia', indonesia)
     router.get('/cecan/korea', korea)
     router.get('/cecan/japan', japan)
     router.get('/cecan/thailand', thailand)
     router.get('/cecan/vietnam', vietnam)
     router.get('/cecan/jeni', jeni)
     router.get('/cecan/jiso', jiso)
     router.get('/cecan/justina', justina)
     router.get('/cecan/rose', rose)
     router.get('/cecan/ryujin', ryujin)

    // Entertainment
     router.get('/entertainment/tebakgambar', tebakgambar)
     router.get('/entertainment/asahotak', asahotak)
     router.get('/entertainment/siapakahaku', siapakahaku)
     router.get('/entertainment/susunkata', susunkata)
     router.get('/entertainment/tebakkata', tebakkata)
     router.get('/entertainment/tebakkalimat', tebakkalimat)
     router.get('/entertainment/tebaktebakan', tebaktebakan)
     router.get('/entertainment/tekateki', tekateki)
     router.get('/entertainment/tebakbendera', tebakbendera)
     router.get('/entertainment/caklontong', caklontong)
     router.get('/entertainment/tebaklirik', tebaklirik)
     router.get('/entertainment/tebakkimia', tebakkimia)
     router.get('/entertainment/family100', family100)
     router.get('/entertainment/tebakkabupaten', tebakkabupaten)
     router.get('/entertainment/truthdare', truthdare)
     router.get('/entertainment/tebakaplikasi', tebakaplikasi)
     router.get('/entertainment/tebakanime', tebakanime)
     router.get('/entertainment/tebakwaifu', tebakwaifu)
     router.get('/entertainment/tebakjenaka', tebakjenaka)
     router.get('/entertainment/tebaklagu', tebaklagu)

     //Nsfw & Sfw
    router.get('/sfw/waifu', waifu2)
    router.get('/sfw/shinobu', shinobu2)
    router.get('/sfw/neko', neko2)
    router.get('/sfw/hug', hug)
    router.get('/sfw/cry', cry)
    router.get('/sfw/cuddle', cuddle)
    router.get('/sfw/bully', bully)
    router.get('/sfw/megumin', megumin)
    router.get('/sfw/bonk', bonk2)
    router.get('/sfw/slap', slap)
    router.get('/sfw/lick', lick)
    router.get('/sfw/kiss', kiss)
    router.get('/sfw/awoo', awoo)
    router.get('/sfw/smug', smug)    
    router.get('/sfw/pat', pat)
    router.get('/sfw/bite', bite)
    router.get('/sfw/yeet', yeet)
    router.get('/sfw/highfive', highfive)
    router.get('/sfw/nom', nom)
    router.get('/sfw/smile', smile)
    router.get('/sfw/wave', wave)
    router.get('/sfw/blush', blush)
    router.get('/sfw/handhold', handhold)
    router.get('/sfw/glomp', glomp)
    router.get('/sfw/happy', happy)
    router.get('/sfw/dance', dance)
    router.get('/sfw/cringe', cringe)  

    // Primbon
     router.get('/primbon/artinama', artinama)
     router.get('/primbon/artimimpi', artimimpi)
     router.get('/primbon/ramaljodoh', ramaljodoh)
     router.get('/primbon/nomorhoki', nomorhoki)
     router.get('/primbon/zodiak', zodiak)
     router.get('/primbon/kecocokannama', kecocokan_nama)
     router.get('/primbon/kecocokanpasangan', kecocokan_nama_pasangan)
     router.get('/primbon/jadianpernikahan', tanggal_jadian_pernikahan)
     router.get('/primbon/sifatusaha', sifat_usaha_bisnis)
     router.get('/primbon/rejekiweton', rejeki_hoki_weton)
     router.get('/primbon/pekerjaanweton', pekerjaan_weton_lahir)
     router.get('/primbon/ramalnasib', ramalan_nasib)
     router.get('/primbon/potensipenyakit', cek_potensi_penyakit)
     router.get('/primbon/artitarot', arti_kartu_tarot)
     router.get('/primbon/haribaik', petung_hari_baik)
     router.get('/primbon/harisangar', hari_sangar_taliwangke)
     router.get('/primbon/harisial', primbon_hari_naas)
     router.get('/primbon/harinaga', rahasia_naga_hari)
     router.get('/primbon/arahrejeki', primbon_arah_rejeki)
     router.get('/primbon/peruntungan', ramalan_peruntungan)
     router.get('/primbon/wetonjawa', weton_jawa)
     router.get('/primbon/sifatkarakter', sifat_karakter_tanggal_lahir)
     router.get('/primbon/keberuntungan', potensi_keberuntungan)
     router.get('/primbon/memancingikan', primbon_memancing_ikan)
     router.get('/primbon/seberapagay', seberapagay)

     //Cerpen
     router.get('/cerpen', cerpennn)

    // Vokal
     router.get('/vokalgenerator/kataholoh', kataholoh)
     router.get('/vokalgenerator/kataheleh', kataheleh)
     router.get('/vokalgenerator/katahalah', katahalah)
     router.get('/vokalgenerator/katahuluh', katahuluh)
     router.get('/vokalgenerator/katahilih', katahilih)
     
     router.use(function (req, res, next) {
        if (res.statusCode == '200') {
             res.render('notfound', {
             layout: 'notfound'
        })
     }
})

module.exports = router
